name: 'GitHub Actions for Upbound - up project'
description: 'Build Upbound projects using up'
author: 'upbound'

inputs:
  push-project:
    description: 'Push Upbound project'
    default: 'false'
  project-file:
    description: 'Path to project definition file. Default to upbound.yaml'
    default: ''
  repository:
    description:
      'Repository for the built package. Overrides the repository specified in
      the project file.'
    default: ''
  tag:
    description:
      'Tag for the built package. If not provided, a semver tag will be
      generated.'
    default: ''
  public:
    description: 'Create new repositories with public visibility'
    default: 'false'
  skip-login:
    description: 'Skip login'
    default: 'false'

branding:
  color: 'purple'

runs:
  using: node20
  main: dist/index.js
