name: 'GitHub Actions for Upbound - up project'
description: 'Build Upbound projects using up'
author: 'upbound'

inputs:
  push-project:
    description: 'Push Upbound project'
    default: 'false'

branding:
  color: 'purple'

runs:
  using: node20
  main: dist/index.js
